### ISSUE TITLE
run_as_root and /helpers/user-perm-helpers.sh Issue with Compose Service in 3.6.0

### ISSUE THREAD

**Issue by hkirsman** [lando/compose#2]
After upgrading to latest Lando (3.6.0) in Ubuntu I've started to see this error:

	illing mysite_appserver_1 ... 
	Killing mysite_node_1      ... 
	Killing mysite_appserver_1 ... done
	Killing mysite_node_1      ... done
	Starting mysite_node_1            ... done
	Creating mysite_elasticsearch_1   ... done
	Creating mysite_database_1        ... done
	Creating mysite_appserver_nginx_1 ... done
	Creating mysite_chrome_1          ... done
	Starting mysite_appserver_1       ... done
	Creating mysite_mailhog_1         ... done
	Scanning to determine which services are ready... Please standby...
	/helpers/user-perm-helpers.sh: line 13: local: UID: readonly variable
	/helpers/user-perm-helpers.sh: line 37: chsh: command not found
	id: www-data: no such user
	-> Installing analysis-icu
	-> Downloading analysis-icu from opensearch
	[=================================================] 100%?? 
	-> Installed analysis-icu with folder name analysis-icu
	
	
	
Later when when trying some app commands I get:

	> DrupalProject\composer\ScriptHandler::createRequiredFiles

	 // Do you really want to drop all tables in the database drupal8?: yes.                                                

	> ERROR 1045 (28000): Access denied for user 'drupal8'@'172.30.0.3' (using password: YES)
	
	
	
lando rebuild doesn't seem to help. I think lando destroy helped once but I got back to the same situation quite quickly.

This is my .lando.yml

```
name: mysite
recipe: drupal8

config:
  php: '7.4'
  via: nginx
  webroot: web
  database: mariadb:10.3
  xdebug: true
  config:
    php: .lando/php.ini

tooling:
  grumphp:
    description: Runs grumphp commands
    cmd:
      - appserver: ./vendor/bin/grumphp
  codecept:
    cmd:
      - appserver: /app/vendor/bin/codecept --config=/app/codeception.yml
  npm:
    description: Runs npm commands
    service: node
  xdebug-on:
    service: appserver
    description: Enables xdebug for nginx
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disables xdebug for nginx
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root
  xdebug-profiler-on:
    service: appserver
    description: Enable xdebug profiler.
    cmd: echo "xdebug.profiler_enable = 1\\nxdebug.profiler_output_dir = /app" >> /usr/local/etc/php/conf.d/xxx-lando-default.ini && pkill -o -USR2 php-fpm
    user: root
  xdebug-profiler-off:
    service: appserver
    description: Disable xdebug profiler.
    cmd: pkill -o -USR2 php-fpm && cp /usr/local/etc/php/conf.d/xxx-lando-default.ini /tmp/lando.ini && sed -i '/xdebug\.profiler/d' /tmp/lando.ini && cp /tmp/lando.ini /usr/local/etc/php/conf.d/xxx-lando-default.ini
    user: root
  update:
    service: appserver
    description: Run drupal build and update
    cmd: cd /app && drush updb --no-post-updates -y && drush cim -y && drush updb -y
  reset:
    service: appserver
    description: Reset the drupal installation
    cmd: cd /app && composer install && drush sql-drop --yes && gunzip < drupal.sql.gz | drush sqlc && drush updb --no-post-updates -y && drush cim -y && drush updb -y && drush eshd -y && drush eshs -y && drush eshr -y && drush cron
  rebuild_index:
    service: appserver
    description: Rebuild elasticsearch index
    cmd: cd /app && drush eshd -y && drush eshs -y && drush eshr -y && drush cron

services:
  appserver:
    build:
      - composer install
    overrides:
      environment:
        HASH_SALT: notsosecurehash
        ENVIRONMENT_NAME: local
        DB_NAME_DRUPAL: drupal8
        DB_USER_DRUPAL: drupal8
        DB_PASS_DRUPAL: drupal8
        DB_HOST_DRUPAL: database
        DRUSH_OPTIONS_URI: https://mysite.lndo.site
        # ATC_APP_ID: REPLACE_THIS
        # ATC_APP_SECRET: REPLACE_THIS
        # ATC_BASE_URL: REPLACE_THIS
        XDEBUG_MODE:
        # Support debugging Drush with XDEBUG 3.
        PHP_IDE_CONFIG: "serverName=appserver"
  chrome:
    type: compose
    services:
      image: selenium/standalone-chrome
      user: root
      ports:
        - "4444:4444"
      volumes:
        - /dev/shm:/dev/shm
      command: /opt/bin/entry_point.sh
  database:
    portforward: 1355
  elasticsearch:
    type: compose
    run_as_root:
      - |
        /bin/sh -c "
        if [ ! -d '/usr/share/opensearch/plugins/analysis-icu' ]; then
          ./bin/opensearch-plugin install analysis-icu;
        fi
        "
    services:
      user: opensearch
      image: opensearchproject/opensearch:latest
      command: ./opensearch-docker-entrypoint.sh
      ports:
        - "9200:9200"
        - "9300:9300"
    overrides:
      environment:
        discovery.type: single-node
        OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
        DISABLE_SECURITY_PLUGIN: "true"
        ELASTICSEARCH_PLUGINS: "analysis-icu"
  # kibana:
  #   type: compose
  #   services:
  #     image: bitnami/kibana:7.10.2
  #     ports:
  #       - "5601:5601"
  #     depends_on:
  #       - elasticsearch
  #     command: /opt/bitnami/scripts/kibana/entrypoint.sh /opt/bitnami/scripts/kibana/run.sh
  #   overrides:
  #     environment:
  #       KIBANA_ELASTICSEARCH_URL: "http://elasticsearch:9200"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node
    build:
      - npm install

proxy:
  mailhog:
    - mail-mysite.lndo.site
  # kibana:
  #  - kibana-mysite.lndo.site:5601

events:
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cache:rebuild -y && drush @local user:login

# Tested with Lando version
version: v3.0.23
```

.lando/php.ini:
```
[PHP]
xdebug.max_nesting_level = 256
xdebug.show_exception_trace = 0
xdebug.collect_params = 0
; Extra custom Xdebug setting for debug to work in PHPStorm/VSCode.
xdebug.mode = debug
xdebug.client_host = ${LANDO_HOST_IP}
xdebug.client_port = 9003
; Change from yes to trigger if in VSCode.
xdebug.start_with_request = yes
xdebug.log = /tmp/xdebug.log
```

.lando/elasticsearch.yml:
```
discovery:
  type: single-node
  zen:
    minimum_master_nodes: 1
network:
  host: 0.0.0.0
node:
  master: true
  ingest: true
  data: true
path:
  data: /bitnami/elasticsearch/data
plugin:
  mandatory: analysis-icu
```
